### ISSUE TITLE
[bug] 无法解析 Minecraft 1.20.5-pre2 中引入的 `FOLDED` nbt 类型

### ISSUE THREAD

**Issue by tangsu99** [Fallen-Breath/MinecraftDataAPI#13]
#### mcdreforged: 2.13.0
* 已测试使用原版服务端也会出现此问题
#### 描述
* 调用 get_player_info() 方法时未指定 path 参数会解析失败，未测试其他 path 是否会解析失败

问题是在使用插件 [bot](https://mcdreforged.com/zh-CN/plugin/bot)时发现的
https://github.com/AnzhiZhang/MCDReforgedPlugins/blob/8607f611eb3da1706a733dd021e3a75613aff3ab/src/bot/bot/plugin.py#L94-L103
* log: 
```
[Server] [10:17:55] [Server thread/INFO]: <tangsu99> !!bot spawn sj
[MCDR] [10:17:55] [commandSpawn/ERROR] [minecraft_data_api]: [Minecraft Data API] Fail to Convert data "tangsu99 has the following entity data: {foodTickTimer: 0, Absor...": Expecting value: line 1 column 13219 (char 13218)
Exception in thread commandSpawn:
Traceback (most recent call last):
  File "C:\Users\18763\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\18763\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\18763\AppData\Local\Programs\Python\Python39\lib\site-packages\mcdreforged\api\decorator\new_thread.py", line 29, in wrapped_target
    raise e from None
  File "C:\Users\18763\AppData\Local\Programs\Python\Python39\lib\site-packages\mcdreforged\api\decorator\new_thread.py", line 26, in wrapped_target
    self.__return_value = target(*args_, **kwargs_)
  File "plugins\Bot-v1.1.5.mcdr\bot\command_handler.py", line 449, in __command_spawn
  File "plugins\Bot-v1.1.5.mcdr\bot\bot_manager.py", line 197, in spawn
  File "plugins\Bot-v1.1.5.mcdr\bot\plugin.py", line 102, in get_location
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Fallen-Breath** [comment]
请提供发生错误前后，服务端的完整输出，尤其是 `data get entity` 指令的输出

**Comment by tangsu99** [comment]
> 请提供发生错误前后，服务端的完整输出，尤其是 `data get entity` 指令的输出

'''
[Server thread/INFO]: tangsu99 has the following entity data: {Brain: {memories: {}}, HurtByTimestamp: 235878, SleepTimer: 0s, SpawnForced: 0b, Invulnerable: 0b, AbsorptionAmount: 0.0f, abilities: {invulnerable: 0b, mayfly: 0b, instabuild: 0b, walkSpeed: 0.1f, mayBuild: 1b, flying: 0b, flySpeed: 0.05f}, FallDistance: 0.0f, recipeBook: {recipes: ["minecraft:piston", "minecraft:yellow_dye_from_dandelion", "minecraft:charcoal", "minecraft:item_frame", "minecraft:white_banner", "minecraft:smooth_sandstone", "minecraft:loom", "minecraft:smoker", "minecraft:granite_slab_from_granite_stonecutting", "minecraft:stone_pickaxe", "minecraft:glass_pane", "minecraft:granite_stairs_from_granite_stonecutting", "minecraft:wooden_axe", "minecraft:dark_oak_boat", "minecraft:lectern", "minecraft:arrow", "minecraft:oak_fence_gate", "minecraft:white_carpet", "minecraft:iron_nugget", "minecraft:purple_stained_glass", "minecraft:iron_ingot_from_nuggets", "minecraft:birch_fence", "minecraft:red_stained_glass", "minecraft:bamboo_raft", "minecraft:chiseled_bookshelf", "minecraft:ladder", "minecraft:tripwire_hook", "minecraft:trapped_chest", "minecraft:hopper", "minecraft:cut_sandstone_from_sandstone_stonecutting", "minecraft:redstone_torch", "minecraft:sandstone_stairs_from_sandstone_stonecutting", "minecraft:lantern", "minecraft:cobblestone_wall", "minecraft:target", "minecraft:white_concrete_powder", "minecraft:magenta_stained_glass", "minecraft:iron_bars", "minecraft:coal_block", "minecraft:iron_trapdoor", "minecraft:cake", "minecraft:granite_slab", "minecraft:iron_helmet", "minecraft:cherry_boat", "minecraft:stick", "minecraft:leather_chestplate", "minecraft:leather_boots", "minecraft:iron_block", "minecraft:acacia_pressure_plate", "minecraft:lime_concrete_powder", "minecraft:leather_leggings", "minecraft:sandstone_wall_from_sandstone_stonecutting", "minecraft:writable_book", "minecraft:acacia_slab", "minecraft:stone_axe", "minecraft:leather_helmet", "minecraft:oak_wood", "minecraft:emerald_block", "minecraft:barrel", "minecraft:stone", "minecraft:golden_carrot", "minecraft:acacia_button", "minecraft:polished_granite_from_granite_stonecutting", "minecraft:cherry_chest_boat", "minecraft:jungle_chest_boat", "minecraft:baked_potato_from_smoking", "minecraft:iron_sword", "minecraft:yellow_stained_glass", "minecraft:green_stained_glass", "minecraft:light_blue_stained_glass", "minecraft:bamboo_chest_raft", "minecraft:sandstone_slab_from_sandstone_stonecutting", "minecraft:wooden_shovel", "minecraft:fletching_table", "minecraft:baked_potato", "minecraft:green_dye", "minecraft:smithing_table", "minecraft:chiseled_sandstone_from_sandstone_stonecutting", "minecraft:polished_granite_stairs_from_granite_stonecutting", "minecraft:orange_stained_glass", "minecraft:cooked_mutton", "minecraft:pink_concrete_powder", "minecraft:cauldron", "minecraft:heavy_weighted_pressure_plate", "minecraft:cobblestone_stairs", "minecraft:stone_shovel", "minecraft:bookshelf", "minecraft:pink_stained_glass", "minecraft:oak_chest_boat", "minecraft:iron_ingot_from_blasting_raw_iron", "minecraft:magenta_concrete_powder", "minecraft:red_dye_from_poppy", "minecraft:birch_chest_boat", "minecraft:birch_trapdoor", "minecraft:polished_granite_slab_from_granite_stonecutting", "minecraft:sandstone_slab", "minecraft:hay_block", "minecraft:dropper", "minecraft:iron_axe", "minecraft:cobblestone_slab", "minecraft:sandstone_stairs", "minecraft:acacia_door", "minecraft:white_bed", "minecraft:birch_slab", "minecraft:cyan_concrete_powder", "minecraft:acacia_sign", "minecraft:coarse_dirt", "minecraft:minecart", "minecraft:oak_boat", "minecraft:cobblestone_slab_from_cobblestone_stonecutting", "minecraft:mangrove_boat", "minecraft:bread", "minecraft:chest", "minecraft:gray_stained_glass", "minecraft:wooden_pickaxe", "minecraft:powered_rail", "minecraft:torch", "minecraft:acacia_boat", "minecraft:baked_potato_from_campfire_cooking", "minecraft:stone_hoe", "minecraft:jungle_boat", "minecraft:green_concrete_powder", "minecraft:lever", "minecraft:oak_stairs", "minecraft:cooked_mutton_from_campfire_cooking", "minecraft:brown_stained_glass", "minecraft:glass_bottle", "minecraft:iron_ingot_from_smelting_raw_iron", <...>], isBlastingFurnaceFilteringCraftable: 0b, isSmokerGuiOpen: 0b, isFilteringCraftable: 1b, toBeDisplayed: ["minecraft:mangrove_boat", "minecraft:bread", "minecraft:gray_stained_glass", "minecraft:powered_rail", "minecraft:torch", "minecraft:yellow_dye_from_dandelion", "minecraft:charcoal", "minecraft:acacia_boat", "minecraft:baked_potato_from_campfire_cooking", "minecraft:item_frame", "minecraft:jungle_boat", "minecraft:white_banner", "minecraft:green_concrete_powder", "minecraft:smooth_sandstone", "minecraft:smoker", "minecraft:granite_slab_from_granite_stonecutting", "minecraft:glass_pane", "minecraft:granite_stairs_from_granite_stonecutting", "minecraft:cooked_mutton_from_campfire_cooking", "minecraft:brown_stained_glass", "minecraft:dark_oak_boat", "minecraft:lectern", "minecraft:glass_bottle", "minecraft:iron_ingot_from_smelting_raw_iron", "minecraft:arrow", "minecraft:detector_rail", "minecraft:polished_granite", "minecraft:purple_stained_glass", "minecraft:cooked_beef", "minecraft:red_stained_glass", "minecraft:yellow_concrete_powder", "minecraft:bamboo_raft", "minecraft:cooked_mutton_from_smoking", "minecraft:chiseled_bookshelf", "minecraft:repeater", "minecraft:red_concrete_powder", "minecraft:painting", "minecraft:cobblestone_stairs_from_cobblestone_stonecutting", "minecraft:trapped_chest", "minecraft:hopper", "minecraft:glass", "minecraft:cut_sandstone_from_sandstone_stonecutting", "minecraft:sandstone_stairs_from_sandstone_stonecutting", "minecraft:sandstone_wall", "minecraft:lantern", "minecraft:cooked_beef_from_smoking", "minecraft:blue_concrete_powder", "minecraft:blue_stained_glass", "minecraft:target", "minecraft:white_concrete_powder", "minecraft:magenta_stained_glass", "minecraft:coal_block", "minecraft:cake", "minecraft:acacia_trapdoor", "minecraft:acacia_stairs", "minecraft:gray_concrete_powder", "minecraft:granite_slab", "minecraft:cherry_boat", "minecraft:iron_nugget_from_smelting", "minecraft:light_blue_concrete_powder", "minecraft:light_gray_concrete_powder", "minecraft:granite_wall_from_granite_stonecutting", "minecraft:gold_ingot_from_nuggets", "minecraft:granite_stairs", "minecraft:lime_concrete_powder", "minecraft:sandstone_wall_from_sandstone_stonecutting", "minecraft:writable_book", "minecraft:acacia_slab", "minecraft:emerald_block", "minecraft:barrel", "minecraft:stone", "minecraft:golden_carrot", "minecraft:nether_brick", "minecraft:polished_granite_from_granite_stonecutting", "minecraft:iron_nugget_from_blasting", "minecraft:baked_potato_from_smoking", "minecraft:yellow_stained_glass", "minecraft:green_stained_glass", "minecraft:light_blue_stained_glass", "minecraft:carrot_on_a_stick", "minecraft:sandstone_slab_from_sandstone_stonecutting", "minecraft:cut_sandstone", "minecraft:fletching_table", "minecraft:baked_potato", "minecraft:green_dye", "minecraft:black_concrete_powder", "minecraft:chiseled_sandstone_from_sandstone_stonecutting", "minecraft:polished_granite_stairs_from_granite_stonecutting", "minecraft:purple_concrete_powder", "minecraft:light_gray_stained_glass", "minecraft:orange_stained_glass", "minecraft:cooked_mutton", "minecraft:pink_concrete_powder", "minecraft:bookshelf", "minecraft:pink_stained_glass", "minecraft:cobblestone_wall_from_cobblestone_stonecutting", "minecraft:leather_horse_armor", "minecraft:iron_ingot_from_blasting_raw_iron", "minecraft:white_stained_glass_pane", "minecraft:raw_iron_block", "minecraft:enchanting_table", "minecraft:candle", "minecraft:white_stained_glass", "minecraft:spruce_boat", "minecraft:brown_concrete_powder", "minecraft:granite_wall", "minecraft:cooked_beef_from_campfire_cooking", "minecraft:orange_concrete_powder", "minecraft:magenta_concrete_powder", "minecraft:red_dye_from_poppy", "minecraft:cyan_stained_glass", "minecraft:polished_granite_slab_from_granite_stonecutting", "minecraft:campfire", "minecraft:sandstone_slab", "minecraft:hay_block", "minecraft:acacia_fence", "minecraft:sandstone_stairs", "minecraft:acacia_door", "minecraft:lime_stained_glass", "minecraft:cut_sandstone_slab_from_sandstone_stonecutting", "minecraft:white_bed", "minecraft:cyan_concrete_powder", "minecraft:acacia_fence_gate", "minecraft:acacia_sign", "minecraft:coarse_dirt", "minecraft:cobblestone_slab_from_cobblestone_stonecutting", "minecraft:black_stained_glass"], isFurnaceGuiOpen: 0b, isGuiOpen: 1b, isFurnaceFilteringCraftable: 0b, isBlastingFurnaceGuiOpen: 0b, isSmokerFilteringCraftable: 0b}, XpTotal: 7161, UUID: [I; -1204460058, -1328528795, -1152385611, -389020075], Tags: ["scbd_synced"], SpawnY: 264, SpawnZ: 883, SpawnX: -1289, ignore_fall_damage_from_current_explosion: 0b, Air: 300s, SpawnAngle: 179.8852f, warden_spawn_tracker: {warning_level: 0, ticks_since_last_warning: 5174, cooldown_ticks: 0}, Score: 7161, Pos: [-1288.5787362134784d, 264.0d, 888.3418783168831d], XpP: 0.77988976f, EnderItems: [], DataVersion: 3953, spawn_extra_particles_on_fall: 0b, HurtTime: 0s, SelectedItemSlot: 0, Inventory: [{count: 1, Slot: 0b, components: {"minecraft:enchantments": {levels: {"minecraft:looting": 3, "minecraft:sharpness": 5, "minecraft:sweeping_edge": 3, "minecraft:unbreaking": 3}}, "minecraft:damage": 3, "minecraft:repair_cost": 15}, id: "minecraft:diamond_sword"}, {count: 1, Slot: 1b, components: {"minecraft:enchantments": {levels: {"minecraft:sharpness": 5, "minecraft:efficiency": 5, "minecraft:mending": 1, "minecraft:unbreaking": 3}}, "minecraft:damage": 7, "minecraft:repair_cost": 15}, id: "minecraft:diamond_axe"}, {count: 1, Slot: 2b, components: {"minecraft:enchantments": {levels: {"minecraft:efficiency": 5, "minecraft:mending": 1, "minecraft:silk_touch": 1, "minecraft:unbreaking": 3}}, "minecraft:damage": 80, "minecraft:repair_cost": 15}, id: "minecraft:diamond_pickaxe"}, {count: 43, Slot: 3b, id: "minecraft:golden_carrot"}, {count: 3, Slot: 4b, id: "minecraft:white_stained_glass"}, {count: 1, Slot: 9b, components: {"minecraft:enchantments": {levels: {"minecraft:mending": 1, "minecraft:unbreaking": 3}}, "minecraft:repair_cost": 3}, id: "minecraft:elytra"}, {count: 29, Slot: 10b, id: "minecraft:stick"}, {count: 1, Slot: 11b, id: "minecraft:water_bucket"}, {count: 6, Slot: 12b, id: "minecraft:oak_planks"}, {count: 11, Slot: 13b, id: "minecraft:oak_log"}, {count: 64, Slot: 14b, id: "minecraft:firework_rocket"}, {count: 64, Slot: 15b, id: "minecraft:firework_rocket"}, {count: 16, Slot: 16b, id: "minecraft:cobblestone"}, {count: 1, Slot: 17b, components: {"minecraft:damage": 92}, id: "minecraft:diamond_hoe"}, {count: 1, Slot: 18b, components: {"minecraft:enchantments": {levels: {"minecraft:efficiency": 1}}, "minecraft:damage": 560}, id: "minecraft:diamond_shovel"}, {count: 1, Slot: 100b, components: {"minecraft:enchantments": {levels: {"minecraft:feather_falling": 4, "minecraft:mending": 1, "minecraft:protection": 4, "minecraft:unbreaking": 3}}, "minecraft:damage": 1, "minecraft:repair_cost": 15}, id: "minecraft:diamond_boots"}, {count: 1, Slot: 101b, components: {"minecraft:enchantments": {levels: {"minecraft:mending": 1, "minecraft:protection": 4, "minecraft:unbreaking": 3}}, "minecraft:damage": 4, "minecraft:repair_cost": 7}, id: "minecraft:diamond_leggings"}, {count: 1, Slot: 102b, components: {"minecraft:enchantments": {levels: {"minecraft:mending": 1, "minecraft:protection": 4, "minecraft:unbreaking": 3}}, "minecraft:damage": 5, "minecraft:repair_cost": 7}, id: "minecraft:diamond_chestplate"}, {count: 1, Slot: 103b, components: {"minecraft:enchantments": {levels: {"minecraft:mending": 1, "minecraft:protection": 4, "minecraft:unbreaking": 3}}, "minecraft:damage": 5, "minecraft:repair_cost": 7}, id: "minecraft:diamond_helmet"}], LastDeathLocation: {pos: [I; -1304, 74, 890], dimension: "minecraft:overworld"}, foodTickTimer: 0, FallFlying: 0b, PortalCooldown: 0, DeathTime: 0s, XpSeed: 2100297671, playerGameType: 0, SpawnDimension: "minecraft:overworld", SelectedItem: {components: {"minecraft:enchantments": {levels: {"minecraft:looting": 3, "minecraft:sharpness": 5, "minecraft:sweeping_edge": 3, "minecraft:unbreaking": 3}}, "minecraft:damage": 3, "minecraft:repair_cost": 15}, count: 1, id: "minecraft:diamond_sword"}, seenCredits: 0b, Motion: [0.0d, -0.0784000015258789d, 0.0d], Health: 20.0f, foodSaturationLevel: 0.40000057f, OnGround: 1b, Dimension: "minecraft:overworld", Rotation: [179.39943f, 23.099867f], XpLevel: 0, current_impulse_context_reset_grace_time: 0, Fire: -20s, attributes: [{id: "minecraft:player.sweeping_damage_ratio", base: 0.0d}, {id: "minecraft:generic.attack_speed", base: 4.0d}, {id: "minecraft:generic.burning_time", base: 1.0d}, {id: "minecraft:generic.movement_speed", base: 0.10000000149011612d}, {id: "minecraft:player.mining_efficiency", base: 0.0d}, {id: "minecraft:generic.armor", base: 0.0d}, {id: "minecraft:generic.attack_damage", base: 1.0d}, {id: "minecraft:player.entity_interaction_range", base: 3.0d}, {id: "minecraft:player.block_interaction_range", base: 4.5d}, {id: "minecraft:generic.oxygen_bonus", base: 0.0d}, {id: "minecraft:player.submerged_mining_speed", base: 0.2d}, {id: "minecraft:generic.armor_toughness", base: 0.0d}], foodLevel: 20, foodExhaustionLevel: 3.5334918f}', content='tangsu99 has the following entity data: {Brain: {memories: {}}, HurtByTimestamp: 235878, SleepTimer: 0s, SpawnForced: 0b, Invulnerable: 0b, AbsorptionAmount: 0.0f, abilities: {invulnerable: 0b, mayfly: 0b, instabuild: 0b, walkSpeed: 0.1f, mayBuild: 1b, flying: 0b, flySpeed: 0.05f}, FallDistance: 0.0f, recipeBook: {recipes: ["minecraft:piston", "minecraft:yellow_dye_from_dandelion", "minecraft:charcoal", "minecraft:item_frame", "minecraft:white_banner", "minecraft:smooth_sandstone", "minecraft:loom", "minecraft:smoker", "minecraft:granite_slab_from_granite_stonecutting", "minecraft:stone_pickaxe", "minecraft:glass_pane", "minecraft:granite_stairs_from_granite_stonecutting", "minecraft:wooden_axe", "minecraft:dark_oak_boat", "minecraft:lectern", "minecraft:arrow", "minecraft:oak_fence_gate", "minecraft:white_carpet", "minecraft:iron_nugget", "minecraft:purple_stained_glass", "minecraft:iron_ingot_from_nuggets", "minecraft:birch_fence", "minecraft:red_stained_glass", "minecraft:bamboo_raft", "minecraft:chiseled_bookshelf", "minecraft:ladder", "minecraft:tripwire_hook", "minecraft:trapped_chest", "minecraft:hopper", "minecraft:cut_sandstone_from_sandstone_stonecutting", "minecraft:redstone_torch", "minecraft:sandstone_stairs_from_sandstone_stonecutting", "minecraft:lantern", "minecraft:cobblestone_wall", "minecraft:target", "minecraft:white_concrete_powder", "minecraft:magenta_stained_glass", "minecraft:iron_bars", "minecraft:coal_block", "minecraft:iron_trapdoor", "minecraft:cake", "minecraft:granite_slab", "minecraft:iron_helmet", "minecraft:cherry_boat", "minecraft:stick", "minecraft:leather_chestplate", "minecraft:leather_boots", "minecraft:iron_block", "minecraft:acacia_pressure_plate", "minecraft:lime_concrete_powder", "minecraft:leather_leggings", "minecraft:sandstone_wall_from_sandstone_stonecutting", "minecraft:writable_book", "minecraft:acacia_slab", "minecraft:stone_axe", "minecraft:leather_helmet", "minecraft:oak_wood", "minecraft:emerald_block", "minecraft:barrel", "minecraft:stone", "minecraft:golden_carrot", "minecraft:acacia_button", "minecraft:polished_granite_from_granite_stonecutting", "minecraft:cherry_chest_boat", "minecraft:jungle_chest_boat", "minecraft:baked_potato_from_smoking", "minecraft:iron_sword", "minecraft:yellow_stained_glass", "minecraft:green_stained_glass", "minecraft:light_blue_stained_glass", "minecraft:bamboo_chest_raft", "minecraft:sandstone_slab_from_sandstone_stonecutting", "minecraft:wooden_shovel", "minecraft:fletching_table", "minecraft:baked_potato", "minecraft:green_dye", "minecraft:smithing_table", "minecraft:chiseled_sandstone_from_sandstone_stonecutting", "minecraft:polished_granite_stairs_from_granite_stonecutting", "minecraft:orange_stained_glass", "minecraft:cooked_mutton", "minecraft:pink_concrete_powder", "minecraft:cauldron", "minecraft:heavy_weighted_pressure_plate", "minecraft:cobblestone_stairs", "minecraft:stone_shovel", "minecraft:bookshelf", "minecraft:pink_stained_glass", "minecraft:oak_chest_boat", "minecraft:iron_ingot_from_blasting_raw_iron", "minecraft:magenta_concrete_powder", "minecraft:red_dye_from_poppy", "minecraft:birch_chest_boat", "minecraft:birch_trapdoor", "minecraft:polished_granite_slab_from_granite_stonecutting", "minecraft:sandstone_slab", "minecraft:hay_block", "minecraft:dropper", "minecraft:iron_axe", "minecraft:cobblestone_slab", "minecraft:sandstone_stairs", "minecraft:acacia_door", "minecraft:white_bed", "minecraft:birch_slab", "minecraft:cyan_concrete_powder", "minecraft:acacia_sign", "minecraft:coarse_dirt", "minecraft:minecart", "minecraft:oak_boat", "minecraft:cobblestone_slab_from_cobblestone_stonecutting", "minecraft:mangrove_boat", "minecraft:bread", "minecraft:chest", "minecraft:gray_stained_glass", "minecraft:wooden_pickaxe", "minecraft:powered_rail", "minecraft:torch", "minecraft:acacia_boat", "minecraft:baked_potato_from_campfire_cooking", "minecraft:stone_hoe", "minecraft:jungle_boat", "minecraft:green_concrete_powder", "minecraft:lever", "minecraft:oak_stairs", "minecraft:cooked_mutton_from_campfire_cooking", "minecraft:brown_stained_glass", "minecraft:glass_bottle", "minecraft:iron_ingot_from_smelting_raw_iron", <...>], isBlastingFurnaceFilteringCraftable: 0b, isSmokerGuiOpen: 0b, isFilteringCraftable: 1b, toBeDisplayed: ["minecraft:mangrove_boat", "minecraft:bread", "minecraft:gray_stained_glass", "minecraft:powered_rail", "minecraft:torch", "minecraft:yellow_dye_from_dandelion", "minecraft:charcoal", "minecraft:acacia_boat", "minecraft:baked_potato_from_campfire_cooking", "minecraft:item_frame", "minecraft:jungle_boat", "minecraft:white_banner", "minecraft:green_concrete_powder", "minecraft:smooth_sandstone", "minecraft:smoker", "minecraft:granite_slab_from_granite_stonecutting", "minecraft:glass_pane", "minecraft:granite_stairs_from_granite_stonecutting", "minecraft:cooked_mutton_from_campfire_cooking", "minecraft:brown_stained_glass", "minecraft:dark_oak_boat", "minecraft:lectern", "minecraft:glass_bottle", "minecraft:iron_ingot_from_smelting_raw_iron", "minecraft:arrow", "minecraft:detector_rail", "minecraft:polished_granite", "minecraft:purple_stained_glass", "minecraft:cooked_beef", "minecraft:red_stained_glass", "minecraft:yellow_concrete_powder", "minecraft:bamboo_raft", "minecraft:cooked_mutton_from_smoking", "minecraft:chiseled_bookshelf", "minecraft:repeater", "minecraft:red_concrete_powder", "minecraft:painting", "minecraft:cobblestone_stairs_from_cobblestone_stonecutting", "minecraft:trapped_chest", "minecraft:hopper", "minecraft:glass", "minecraft:cut_sandstone_from_sandstone_stonecutting", "minecraft:sandstone_stairs_from_sandstone_stonecutting", "minecraft:sandstone_wall", "minecraft:lantern", "minecraft:cooked_beef_from_smoking", "minecraft:blue_concrete_powder", "minecraft:blue_stained_glass", "minecraft:target", "minecraft:white_concrete_powder", "minecraft:magenta_stained_glass", "minecraft:coal_block", "minecraft:cake", "minecraft:acacia_trapdoor", "minecraft:acacia_stairs", "minecraft:gray_concrete_powder", "minecraft:granite_slab", "minecraft:cherry_boat", "minecraft:iron_nugget_from_smelting", "minecraft:light_blue_concrete_powder", "minecraft:light_gray_concrete_powder", "minecraft:granite_wall_from_granite_stonecutting", "minecraft:gold_ingot_from_nuggets", "minecraft:granite_stairs", "minecraft:lime_concrete_powder", "minecraft:sandstone_wall_from_sandstone_stonecutting", "minecraft:writable_book", "minecraft:acacia_slab", "minecraft:emerald_block", "minecraft:barrel", "minecraft:stone", "minecraft:golden_carrot", "minecraft:nether_brick", "minecraft:polished_granite_from_granite_stonecutting", "minecraft:iron_nugget_from_blasting", "minecraft:baked_potato_from_smoking", "minecraft:yellow_stained_glass", "minecraft:green_stained_glass", "minecraft:light_blue_stained_glass", "minecraft:carrot_on_a_stick", "minecraft:sandstone_slab_from_sandstone_stonecutting", "minecraft:cut_sandstone", "minecraft:fletching_table", "minecraft:baked_potato", "minecraft:green_dye", "minecraft:black_concrete_powder", "minecraft:chiseled_sandstone_from_sandstone_stonecutting", "minecraft:polished_granite_stairs_from_granite_stonecutting", "minecraft:purple_concrete_powder", "minecraft:light_gray_stained_glass", "minecraft:orange_stained_glass", "minecraft:cooked_mutton", "minecraft:pink_concrete_powder", "minecraft:bookshelf", "minecraft:pink_stained_glass", "minecraft:cobblestone_wall_from_cobblestone_stonecutting", "minecraft:leather_horse_armor", "minecraft:iron_ingot_from_blasting_raw_iron", "minecraft:white_stained_glass_pane", "minecraft:raw_iron_block", "minecraft:enchanting_table", "minecraft:candle", "minecraft:white_stained_glass", "minecraft:spruce_boat", "minecraft:brown_concrete_powder", "minecraft:granite_wall", "minecraft:cooked_beef_from_campfire_cooking", "minecraft:orange_concrete_powder", "minecraft:magenta_concrete_powder", "minecraft:red_dye_from_poppy", "minecraft:cyan_stained_glass", "minecraft:polished_granite_slab_from_granite_stonecutting", "minecraft:campfire", "minecraft:sandstone_slab", "minecraft:hay_block", "minecraft:acacia_fence", "minecraft:sandstone_stairs", "minecraft:acacia_door", "minecraft:lime_stained_glass", "minecraft:cut_sandstone_slab_from_sandstone_stonecutting", "minecraft:white_bed", "minecraft:cyan_concrete_powder", "minecraft:acacia_fence_gate", "minecraft:acacia_sign", "minecraft:coarse_dirt", "minecraft:cobblestone_slab_from_cobblestone_stonecutting", "minecraft:black_stained_glass"], isFurnaceGuiOpen: 0b, isGuiOpen: 1b, isFurnaceFilteringCraftable: 0b, isBlastingFurnaceGuiOpen: 0b, isSmokerFilteringCraftable: 0b}, XpTotal: 7161, UUID: [I; -1204460058, -1328528795, -1152385611, -389020075], Tags: ["scbd_synced"], SpawnY: 264, SpawnZ: 883, SpawnX: -1289, ignore_fall_damage_from_current_explosion: 0b, Air: 300s, SpawnAngle: 179.8852f, warden_spawn_tracker: {warning_level: 0, ticks_since_last_warning: 5174, cooldown_ticks: 0}, Score: 7161, Pos: [-1288.5787362134784d, 264.0d, 888.3418783168831d], XpP: 0.77988976f, EnderItems: [], DataVersion: 3953, spawn_extra_particles_on_fall: 0b, HurtTime: 0s, SelectedItemSlot: 0, Inventory: [{count: 1, Slot: 0b, components: {"minecraft:enchantments": {levels: {"minecraft:looting": 3, "minecraft:sharpness": 5, "minecraft:sweeping_edge": 3, "minecraft:unbreaking": 3}}, "minecraft:damage": 3, "minecraft:repair_cost": 15}, id: "minecraft:diamond_sword"}, {count: 1, Slot: 1b, components: {"minecraft:enchantments": {levels: {"minecraft:sharpness": 5, "minecraft:efficiency": 5, "minecraft:mending": 1, "minecraft:unbreaking": 3}}, "minecraft:damage": 7, "minecraft:repair_cost": 15}, id: "minecraft:diamond_axe"}, {count: 1, Slot: 2b, components: {"minecraft:enchantments": {levels: {"minecraft:efficiency": 5, "minecraft:mending": 1, "minecraft:silk_touch": 1, "minecraft:unbreaking": 3}}, "minecraft:damage": 80, "minecraft:repair_cost": 15}, id: "minecraft:diamond_pickaxe"}, {count: 43, Slot: 3b, id: "minecraft:golden_carrot"}, {count: 3, Slot: 4b, id: "minecraft:white_stained_glass"}, {count: 1, Slot: 9b, components: {"minecraft:enchantments": {levels: {"minecraft:mending": 1, "minecraft:unbreaking": 3}}, "minecraft:repair_cost": 3}, id: "minecraft:elytra"}, {count: 29, Slot: 10b, id: "minecraft:stick"}, {count: 1, Slot: 11b, id: "minecraft:water_bucket"}, {count: 6, Slot: 12b, id: "minecraft:oak_planks"}, {count: 11, Slot: 13b, id: "minecraft:oak_log"}, {count: 64, Slot: 14b, id: "minecraft:firework_rocket"}, {count: 64, Slot: 15b, id: "minecraft:firework_rocket"}, {count: 16, Slot: 16b, id: "minecraft:cobblestone"}, {count: 1, Slot: 17b, components: {"minecraft:damage": 92}, id: "minecraft:diamond_hoe"}, {count: 1, Slot: 18b, components: {"minecraft:enchantments": {levels: {"minecraft:efficiency": 1}}, "minecraft:damage": 560}, id: "minecraft:diamond_shovel"}, {count: 1, Slot: 100b, components: {"minecraft:enchantments": {levels: {"minecraft:feather_falling": 4, "minecraft:mending": 1, "minecraft:protection": 4, "minecraft:unbreaking": 3}}, "minecraft:damage": 1, "minecraft:repair_cost": 15}, id: "minecraft:diamond_boots"}, {count: 1, Slot: 101b, components: {"minecraft:enchantments": {levels: {"minecraft:mending": 1, "minecraft:protection": 4, "minecraft:unbreaking": 3}}, "minecraft:damage": 4, "minecraft:repair_cost": 7}, id: "minecraft:diamond_leggings"}, {count: 1, Slot: 102b, components: {"minecraft:enchantments": {levels: {"minecraft:mending": 1, "minecraft:protection": 4, "minecraft:unbreaking": 3}}, "minecraft:damage": 5, "minecraft:repair_cost": 7}, id: "minecraft:diamond_chestplate"}, {count: 1, Slot: 103b, components: {"minecraft:enchantments": {levels: {"minecraft:mending": 1, "minecraft:protection": 4, "minecraft:unbreaking": 3}}, "minecraft:damage": 5, "minecraft:repair_cost": 7}, id: "minecraft:diamond_helmet"}], LastDeathLocation: {pos: [I; -1304, 74, 890], dimension: "minecraft:overworld"}, foodTickTimer: 0, FallFlying: 0b, PortalCooldown: 0, DeathTime: 0s, XpSeed: 2100297671, playerGameType: 0, SpawnDimension: "minecraft:overworld", SelectedItem: {components: {"minecraft:enchantments": {levels: {"minecraft:looting": 3, "minecraft:sharpness": 5, "minecraft:sweeping_edge": 3, "minecraft:unbreaking": 3}}, "minecraft:damage": 3, "minecraft:repair_cost": 15}, count: 1, id: "minecraft:diamond_sword"}, seenCredits: 0b, Motion: [0.0d, -0.0784000015258789d, 0.0d], Health: 20.0f, foodSaturationLevel: 0.40000057f, OnGround: 1b, Dimension: "minecraft:overworld", Rotation: [179.39943f, 23.099867f], XpLevel: 0, current_impulse_context_reset_grace_time: 0, Fire: -20s, attributes: [{id: "minecraft:player.sweeping_damage_ratio", base: 0.0d}, {id: "minecraft:generic.attack_speed", base: 4.0d}, {id: "minecraft:generic.burning_time", base: 1.0d}, {id: "minecraft:generic.movement_speed", base: 0.10000000149011612d}, {id: "minecraft:player.mining_efficiency", base: 0.0d}, {id: "minecraft:generic.armor", base: 0.0d}, {id: "minecraft:generic.attack_damage", base: 1.0d}, {id: "minecraft:player.entity_interaction_range", base: 3.0d}, {id: "minecraft:player.block_interaction_range", base: 4.5d}, {id: "minecraft:generic.oxygen_bonus", base: 0.0d}, {id: "minecraft:player.submerged_mining_speed", base: 0.2d}, {id: "minecraft:generic.armor_toughness", base: 0.0d}], foodLevel: 20, foodExhaustionLevel: 3.5334918f}', source=<InfoSource.SERVER: 0>, logging_level='INFO')]
[MCDR] [2024-07-09 11:10:35.383] [commandSpawn/ERROR] [player_data_getter.py:52(get_player_info)] [minecraft_data_api]: [Minecraft Data API] Fail to Convert data "tangsu99 has the following entity data: {Brain: {memories: {}}, ...": Expecting value: line 1 column 13216 (char 13215)
'''
[MCDR.log](https://github.com/user-attachments/files/16137208/MCDR.log)

**Comment by Fallen-Breath** [comment]
确认问题字段，玩家配方书字段里，出现了形如 `{recipeBook: {recipes: ["minecraft:piston", <...>]}}` 的输出。这里 `<...>` 显然不是合法的 json 结构，因而导致了解析失败

**Comment by Fallen-Breath** [comment]
这种类型是 Minecraft 1.20.5-pre2 中引入的 `FOLDED` nbt 类型，会在 list 长度超过一定值、compound 嵌套深度到达一定值后出现（常见的阈值为 64、128），用于截断输出，用于避免输出过长
