### ISSUE TITLE
如何在 on_xxx 事件处理函数中使用 DataAPI

### ISSUE THREAD

**Issue by iBug** [Fallen-Breath/MinecraftDataAPI#8]
我尝试在有人登录的时候（`def on_player_joined`）获取在线人数，但是遇到了下面这个错误。如何才能在这种情况下使用相关 API？

https://github.com/MCDReforged/MinecraftDataAPI/blob/db721f11074608a906ae4a65408b1e16821bd8a8/MinecraftDataAPI.py#L167-L168

**Comment by Fallen-Breath** [comment]
你无法在 on_xxx 事件监听器函数中直接调用所述函数。请在其他线程调用，如即时开启一个线程并在其中执行逻辑，或者通过队列等数据结构将请求传递给自定义工作线程
